name: Internal - Epic
description: Describe an a group of related stories or tasks
type: Epic
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of the epic
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: What conditions must be satisfied to consider this epic done?
    validations:
      required: true
