/**
 * seed-d1.ts
 *
 * ETL: reads evictions.db + analysis/outputs/csa_features.csv
 *      → writes seed.sql for `wrangler d1 execute evictions --local --file=seed.sql`
 *
 * Usage:
 *   npx tsx scripts/seed-d1.ts
 *   wrangler d1 execute evictions --local --file=seed.sql
 */

import Database from "better-sqlite3";
import { createHash } from "crypto";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const DB_PATH = resolve(ROOT, "evictions.db");
const CSA_FEATURES_PATH = resolve(ROOT, "analysis/outputs/csa_features.csv");
const TRACT_CSA_PATH = resolve(ROOT, "analysis/data/tract_to_csa.csv");
const BNIA_PATH = resolve(ROOT, "data/bnia_evictions.csv");
const JSON_DIR = resolve(ROOT, "data/json");
const OUT_PATH = resolve(ROOT, "seed.sql");

// ─── Helpers ──────────────────────────────────────────────────────────────

function hashName(name: string): string {
  return createHash("sha256").update(name).digest("hex").slice(0, 16);
}

function truncateAddress(street: string | null, zip: string | null): string {
  if (!street) return zip ?? "";
  const withoutNumber = street.replace(/^\d+[-\d/]*\s+/, "").trim();
  const titled = withoutNumber
    .toLowerCase()
    .replace(/\b\w/g, (c) => c.toUpperCase());
  return zip ? `${titled} ${zip}` : titled;
}

function esc(val: string | null | undefined): string {
  if (val === null || val === undefined) return "NULL";
  return `'${String(val).replace(/'/g, "''")}'`;
}

function parseCsv(content: string): Record<string, string>[] {
  const lines = content.trim().split("\n");
  // Strip BOM if present
  const header = lines[0].replace(/^\uFEFF/, "").split(",");
  return lines.slice(1).map((line) => {
    const vals = line.split(",");
    return Object.fromEntries(
      header.map((h, i) => [h.trim(), (vals[i] ?? "").trim()])
    );
  });
}

// ─── Load source data ──────────────────────────────────────────────────────

console.log("Opening evictions.db...");
const db = new Database(DB_PATH, { readonly: true });

// Tract → CSA crosswalk
const tractCsa = parseCsv(readFileSync(TRACT_CSA_PATH, "utf-8"));
const tractToCSA: Map<string, string> = new Map(
  tractCsa.map((r) => [
    String(r["GEOID_Tract_2020"]).padStart(11, "0"),
    r["Community_Statistical_Area_2010"],
  ])
);

// Evicted case numbers
const evictedSet = new Set<string>(
  (
    db
      .prepare(
        `SELECT DISTINCT c.case_number
         FROM case_events ce
         JOIN cases c ON ce.case_id = c.id
         WHERE ce.event_type = 'Warrant of Restitution - Return of Service - Evicted'`
      )
      .all() as { case_number: string }[]
  ).map((r) => r.case_number)
);

console.log(`  Evicted cases: ${evictedSet.size}`);

// CSA features CSV
const csaRows = parseCsv(readFileSync(CSA_FEATURES_PATH, "utf-8"));
console.log(`  CSA feature rows: ${csaRows.length}`);

// BNIA eviction rate (evict23) — optional, keyed by CSA2010 name
const bniaRateMap = new Map<string, number>();
if (existsSync(BNIA_PATH)) {
  const bniaRows = parseCsv(readFileSync(BNIA_PATH, "utf-8"));
  for (const r of bniaRows) {
    const key = (r["CSA2010"] ?? "").trim();
    const rate = parseFloat(r["evict23"] ?? "");
    if (key && !isNaN(rate)) bniaRateMap.set(key, rate);
  }
  console.log(`  BNIA eviction rate rows: ${bniaRateMap.size}`);
} else {
  console.log("  BNIA CSV not found — bnia_eviction_rate will be NULL");
}

// ─── Build SQL ─────────────────────────────────────────────────────────────

const lines: string[] = [];

lines.push("-- Generated by scripts/seed-d1.ts");
lines.push("-- Run: wrangler d1 execute evictions --local --file=seed.sql");
lines.push("");

// Schema
lines.push(`DROP TABLE IF EXISTS cases_public;`);
lines.push(`DROP TABLE IF EXISTS csa_features;`);
lines.push(`DROP TABLE IF EXISTS landlord_csa;`);
lines.push(`DROP TABLE IF EXISTS monthly_counts;`);
lines.push("");

lines.push(`CREATE TABLE cases_public (
  case_id TEXT PRIMARY KEY,
  case_type TEXT,
  filing_date TEXT,
  plaintiff TEXT,
  address_public TEXT,
  csa TEXT,
  judgment TEXT,
  eviction_executed INTEGER DEFAULT 0,
  defendant_hash TEXT,
  details_json TEXT
);`);

lines.push(`CREATE TABLE csa_features (
  csa TEXT PRIMARY KEY,
  eviction_count INTEGER,
  total_pop REAL,
  total_hh REAL,
  renter_hh REAL,
  total_rental_units REAL,
  eviction_rate_per_1k_residents REAL,
  eviction_rate_per_1k_renter_hh REAL,
  ownership_concentration_pct REAL,
  unique_owners INTEGER,
  pct_black_non_hisp REAL,
  pct_white_non_hisp REAL,
  median_hh_income REAL,
  pct_hh_income_under_25k REAL,
  unemployment_rate REAL,
  bnia_eviction_rate REAL
);`);

lines.push(`CREATE TABLE landlord_csa (
  csa TEXT,
  plaintiff TEXT,
  warrant_count INTEGER,
  eviction_count INTEGER,
  PRIMARY KEY (csa, plaintiff)
);`);

lines.push(`CREATE TABLE monthly_counts (
  month TEXT PRIMARY KEY,
  warrant_count INTEGER,
  eviction_count INTEGER
);`);
lines.push("");

// ─── cases_public ──────────────────────────────────────────────────────────

console.log("Building cases_public...");

// Get all December 2024 warrant cases with tenant address + landlord name
const warrantCases = db
  .prepare(
    `SELECT DISTINCT
       c.case_number,
       c.filing_date,
       ct.name AS case_type,
       cs.name AS case_status,
       cp_l.name AS plaintiff,
       cp_t.name AS tenant_name,
       a.street, a.zip_code,
       a.census_tract
     FROM warrant_filings w
     JOIN cases c ON w.case_number = c.case_number
     LEFT JOIN case_types ct ON c.case_type_id = ct.id
     LEFT JOIN case_statuses cs ON c.case_status_id = cs.id
     LEFT JOIN case_parties cp_l ON cp_l.case_id = c.id AND cp_l.party_type = 'landlord'
     LEFT JOIN case_parties cp_t ON cp_t.case_id = c.id AND cp_t.party_type = 'tenant'
     LEFT JOIN addresses a ON cp_t.address_id = a.id
     WHERE strftime('%Y-%m', w.event_date) = '2024-12'`
  )
  .all() as {
  case_number: string;
  filing_date: string | null;
  case_type: string | null;
  case_status: string | null;
  plaintiff: string | null;
  tenant_name: string | null;
  street: string | null;
  zip_code: string | null;
  census_tract: string | null;
}[];

console.log(`  December 2024 warrant cases: ${warrantCases.length}`);

let inserted = 0;
for (const row of warrantCases) {
  // CSA via census tract
  let csa: string | null = null;
  if (row.census_tract) {
    const geoid = `24510${String(row.census_tract).padStart(6, "0")}`;
    csa = tractToCSA.get(geoid) ?? null;
  }

  const addressPublic = truncateAddress(row.street, row.zip_code);
  const tenantHash = row.tenant_name ? hashName(row.tenant_name) : null;
  const evicted = evictedSet.has(row.case_number) ? 1 : 0;

  // Load details JSON if available
  let detailsJson: string | null = null;
  const jsonPath = resolve(JSON_DIR, `${row.case_number}.json`);
  if (existsSync(jsonPath)) {
    try {
      const raw = JSON.parse(readFileSync(jsonPath, "utf-8"));
      // Redact tenant name from JSON
      if (row.tenant_name && tenantHash) {
        const str = JSON.stringify(raw).replaceAll(
          row.tenant_name,
          `[REDACTED:${tenantHash}]`
        );
        detailsJson = str;
      } else {
        detailsJson = JSON.stringify(raw);
      }
    } catch {
      // skip malformed JSON
    }
  }

  lines.push(
    `INSERT OR IGNORE INTO cases_public VALUES (${esc(row.case_number)}, ${esc(row.case_type)}, ${esc(row.filing_date)}, ${esc(row.plaintiff)}, ${esc(addressPublic)}, ${esc(csa)}, ${esc(row.case_status)}, ${evicted}, ${esc(tenantHash)}, ${esc(detailsJson)});`
  );
  inserted++;
}
console.log(`  Inserted: ${inserted}`);

lines.push("");

// ─── csa_features ─────────────────────────────────────────────────────────

console.log("Building csa_features...");
for (const r of csaRows) {
  const n = (k: string) => {
    const v = parseFloat(r[k]);
    return isNaN(v) ? "NULL" : String(v);
  };
  const csaKey = (r["csa2010"] ?? "").trim();
  const bniaRate = bniaRateMap.has(csaKey)
    ? String(bniaRateMap.get(csaKey))
    : "NULL";
  lines.push(
    `INSERT OR IGNORE INTO csa_features VALUES (${esc(r["csa2010"])}, ${n("eviction_count")}, ${n("total_pop")}, ${n("total_hh")}, ${n("renter_hh")}, ${n("total_rental_units")}, ${n("eviction_rate_per_1k_residents")}, ${n("eviction_rate_per_1k_renter_hh")}, ${n("ownership_concentration_pct")}, ${n("unique_owners")}, ${n("pct_black_non_hisp")}, ${n("pct_white_non_hisp")}, ${n("median_hh_income")}, ${n("pct_hh_income_under_25k")}, ${n("unemployment_rate")}, ${bniaRate});`
  );
}
console.log(`  CSA rows: ${csaRows.length}`);
lines.push("");

// ─── landlord_csa ─────────────────────────────────────────────────────────

console.log("Building landlord_csa...");
const landlordCsa = db
  .prepare(
    `SELECT
       cp.name AS plaintiff,
       a.census_tract,
       COUNT(DISTINCT w.case_number) AS warrant_count,
       SUM(CASE WHEN ev.case_number IS NOT NULL THEN 1 ELSE 0 END) AS eviction_count
     FROM warrant_filings w
     JOIN cases c ON w.case_number = c.case_number
     JOIN case_parties cp ON cp.case_id = c.id AND cp.party_type = 'landlord'
     LEFT JOIN case_parties cp_t ON cp_t.case_id = c.id AND cp_t.party_type = 'tenant'
     LEFT JOIN addresses a ON cp_t.address_id = a.id
     LEFT JOIN (
       SELECT DISTINCT c2.case_number
       FROM case_events ce2
       JOIN cases c2 ON ce2.case_id = c2.id
       WHERE ce2.event_type = 'Warrant of Restitution - Return of Service - Evicted'
     ) ev ON ev.case_number = w.case_number
     WHERE strftime('%Y-%m', w.event_date) = '2024-12'
     GROUP BY cp.name, a.census_tract`
  )
  .all() as {
  plaintiff: string;
  census_tract: string | null;
  warrant_count: number;
  eviction_count: number;
}[];

// Aggregate by CSA
const landlordCsaMap = new Map<
  string,
  Map<string, { warrants: number; evictions: number }>
>();
for (const row of landlordCsa) {
  let csa: string | null = null;
  if (row.census_tract) {
    const geoid = `24510${String(row.census_tract).padStart(6, "0")}`;
    csa = tractToCSA.get(geoid) ?? null;
  }
  if (!csa) continue;
  if (!landlordCsaMap.has(csa)) landlordCsaMap.set(csa, new Map());
  const csaMap = landlordCsaMap.get(csa)!;
  const existing = csaMap.get(row.plaintiff) ?? { warrants: 0, evictions: 0 };
  csaMap.set(row.plaintiff, {
    warrants: existing.warrants + row.warrant_count,
    evictions: existing.evictions + row.eviction_count,
  });
}

let lcRows = 0;
for (const [csa, plaintiffs] of landlordCsaMap) {
  for (const [plaintiff, counts] of plaintiffs) {
    lines.push(
      `INSERT OR IGNORE INTO landlord_csa VALUES (${esc(csa)}, ${esc(plaintiff)}, ${counts.warrants}, ${counts.evictions});`
    );
    lcRows++;
  }
}
console.log(`  landlord_csa rows: ${lcRows}`);
lines.push("");

// ─── monthly_counts ────────────────────────────────────────────────────────

console.log("Building monthly_counts...");
const monthly = db
  .prepare(
    `SELECT
       strftime('%Y-%m', w.event_date) AS month,
       COUNT(DISTINCT w.case_number) AS warrant_count
     FROM warrant_filings w
     WHERE w.event_date IS NOT NULL
     GROUP BY month
     ORDER BY month`
  )
  .all() as { month: string; warrant_count: number }[];

for (const row of monthly) {
  // Count evictions for this month
  const evCount = db
    .prepare(
      `SELECT COUNT(DISTINCT c.case_number) AS cnt
       FROM case_events ce
       JOIN cases c ON ce.case_id = c.id
       JOIN warrant_filings w ON w.case_number = c.case_number
       WHERE ce.event_type = 'Warrant of Restitution - Return of Service - Evicted'
         AND strftime('%Y-%m', w.event_date) = ?`
    )
    .get(row.month) as { cnt: number };
  lines.push(
    `INSERT OR IGNORE INTO monthly_counts VALUES (${esc(row.month)}, ${row.warrant_count}, ${evCount.cnt});`
  );
}
console.log(`  monthly_counts rows: ${monthly.length}`);

// ─── Write output ──────────────────────────────────────────────────────────

writeFileSync(OUT_PATH, lines.join("\n"), "utf-8");
console.log(`\nWrote ${lines.length} lines to ${OUT_PATH}`);
console.log("Next: wrangler d1 execute evictions --local --file=seed.sql");
